### PR TITLE
v0.1.26

### PR DESCRIPTION
**Pull request by greynewell**
- Update URL for servers from previous value to `servers.souls.chat`

## Demo
This demo was recorded using a locally `npm link`ed copy of `soul-engine-cli`.

https://github.com/opensouls/soul-engine/assets/19847545/c7d6abcf-beec-445d-881a-082053f8a963

### CODE REVIEW

**Review by dooart — CHANGES_REQUESTED** [review]
this looks good!

only thing to fix is the versioning - notice how all the packages use the same version? you have to bump them all together

there's a bump script in the main package.json

**Comment by dooart** [comment]
oh i didn't test but i'm assuming that servers.souls.chat is correctly pointing to fly

**Comment by greynewell** [comment]
@dooart done! Thanks for catching that, Thiago. 🤝

**Review by dooart — APPROVED** [review]
neat!

**Review by tobowers — COMMENTED** [review]
~code looks good. Is the DNS up?~ [UPDATE: nm, didn't see it's merged]

**Pull request merged**
