### PR TITLE
Anthropic support

### PR DESCRIPTION
**Pull request by tobowers**
This adds Anthropic support to socialagi.

Also:

* remove legacy tests
* support OSS models that require alternating between user/assistant (Anthropic requires this too)

### CODE REVIEW

**Review by dooart — CHANGES_REQUESTED** [review]
- i think you forgot to export `AnthropicProcessor` in `languageModels/index.ts`
- there might be a bug in `reformatRoles`. i'm getting this error `'messages: first message must use the "user" role'`

**Comment by dooart** [comment]
okay so this worked:
```
reformattedMessages [
  {
    role: 'system',
    content: "(blueprint removed for brevity)",
    name: undefined,
    function_call: undefined
  },
  {
    role: 'user',
    content: 'Model the mind of Freddy.\n' +
      '  \n' +
      '## Instructions\n' +
      '* DO NOT include actions (for example, do NOT add non-verbal items like *John Smiles* or *John Nods*, etc).\n' +
      '* DO NOT include internal thoughts (for example, do NOT respond with John thought: "...").\n' +
      '* If necessary, use all CAPS to emphasize certain words.\n' +
      '\n' +
      'Freddy greets the user and directly asks for 1-3 goals for the day\n' +
      '\n' +
      `Please reply with the next utterance from Freddy. Use the format 'Freddy said: "..."'`,
    name: undefined,
    function_call: undefined
  }
]
```

but this did not:
```
reformattedMessages [
  {
    role: 'system',
    content: "(removed for brevity)",
    name: undefined,
    function_call: undefined
  },
  {
    role: 'assistant',
    content: `Freddy said: "Hey there! I'm stoked to help you crush your goals today. So tell me, what are the top 1-3 things you absolutely want to accomplish before the day is done? Let's get those goals locked in!"`,
    name: undefined,
    function_call: undefined
  },
  {
    role: 'user',
    content: 'user said: walk the dog, buy food\n' +
      '\n' +
      'Model the mind of Freddy.\n' +
      '\n' +
      '## Description\n' +
      'Freddy reflects about their current objective of Objective: collecting user goals\n' +
      'Acceptance criteria: at least 1 goal, no more than 3 goals, and what the user just said\n' +
      '\n' +
      '## Rules\n' +
      '* Internal monologue thoughts should match the speaking style of Freddy.\n' +
      `* Only respond with the format 'Freddy thought: "..."', no additonal commentary or text.\n` +
      '* Follow the Description when creating the internal thought!\n' +
      '\n' +
      `Please reply with the next internal monologue thought of Freddy. Use the format 'Freddy thought: "..."'`,
    name: undefined,
    function_call: undefined
  }
]
```

**Comment by dooart** [comment]
created a repo with the code i used to test:
https://github.com/dooart/assistant-socialagi

**Comment by tobowers** [comment]
@dooart fixorated.

**Review by dooart — APPROVED** [review]
working now!

**Pull request merged**
